-- Databricks notebook source
-- DBTITLE 1,Defining Variables
SET YEAR ='2021';
SET CTDATASET = '/FileStore/tables/clinicaltrial_2021.csv';
SET MESHDATASET = '/FileStore/tables/mesh.csv';
SET PHARMADATASET = '/FileStore/tables/pharma.csv';

-- COMMAND ----------

-- DBTITLE 1,Loading Clinical Trials Dataset into Table
DROP TABLE IF EXISTS CLINICAL_TRIAL;

CREATE TABLE IF NOT EXISTS CLINICAL_TRIAL
USING CSV
OPTIONS (PATH = ${hiveconf:CTDATASET}, DELIMITER = '|', HEADER = 'TRUE');

SELECT * FROM CLINICAL_TRIAL;

-- COMMAND ----------

-- DBTITLE 1,#1. The number of studies in the dataset
SELECT DISTINCT COUNT (Id) No_of_Clinical_Trials 
  FROM CLINICAL_TRIAL

-- COMMAND ----------

-- DBTITLE 1,#2. List of all types of studies and their frequencies
SELECT  TYPE, COUNT (*) AS FREQUENCY FROM CLINICAL_TRIAL
  GROUP BY TYPE
  ORDER BY FREQUENCY DESC;

-- COMMAND ----------

SELECT  TYPE, COUNT (*) AS FREQUENCY FROM CLINICAL_TRIAL
  GROUP BY TYPE
  ORDER BY FREQUENCY DESC;

-- COMMAND ----------

-- DBTITLE 1,#3. The top five (5) conditions with their frequencies
DROP VIEW IF EXISTS CONDITIONS;

CREATE VIEW CONDITIONS AS
  SELECT CONDITIONS, COUNT(*) AS FREQUENCY
  FROM (SELECT EXPLODE(SPLIT(CONDITIONS,',')) AS CONDITIONS
        FROM CLINICAL_TRIAL)
  GROUP BY CONDITIONS
  ORDER BY FREQUENCY DESC;
  
SELECT * FROM CONDITIONS LIMIT 5;

-- COMMAND ----------

-- DBTITLE 1,Loading the Mesh Dataset into a Table
DROP TABLE IF EXISTS MESH;

CREATE TABLE IF NOT EXISTS MESH
USING csv
OPTIONS (PATH = ${hiveconf:MESHDATASET}, DELIMITER = ',', HEADER = "TRUE");

SELECT * FROM MESH;

-- COMMAND ----------

-- DBTITLE 1,#4. The five (5) most frequent roots
DROP VIEW IF EXISTS MESH_RC;

CREATE VIEW MESH_RC AS
SELECT TERM, SUBSTRING(TREE,1,3) AS ROOT_CODES FROM MESH;

SELECT * FROM MESH_RC;

SELECT ROOT_CODES, SUM(FREQUENCY) AS FREQUENCY
  FROM (SELECT M.ROOT_CODES, C.FREQUENCY
          FROM MESH_RC M JOIN CONDITIONS C 
          ON M.TERM = C.CONDITIONS)
  GROUP BY ROOT_CODES  
  ORDER BY FREQUENCY DESC
  LIMIT 5;

-- COMMAND ----------

-- DBTITLE 1,Loading the Pharma Dataset into Table
DROP TABLE IF EXISTS PHARMA;

CREATE TABLE IF NOT EXISTS PHARMA
USING CSV
OPTIONS (PATH = ${hiveconf:PHARMADATASET}, DELIMITER = ',', HEADER = "TRUE");

SELECT * FROM PHARMA

-- COMMAND ----------

-- DBTITLE 1,#5. The Ten(10) most common non-pharmaceutical sponsors companies 
SELECT SPONSOR, COUNT(SPONSOR) AS FREQUENCY
  FROM (SELECT SPONSOR, PARENT_COMPANY
        FROM CLINICAL_TRIAL CT LEFT JOIN PHARMA P
        ON CT.SPONSOR = P.PARENT_COMPANY)
  WHERE PARENT_COMPANY IS NULL 
  GROUP BY SPONSOR  
ORDER BY FREQUENCY DESC
LIMIT 10;

-- COMMAND ----------

-- DBTITLE 1,#6. Completed studies per month
CREATE VIEW COMPLETED_STUDIES_2021 AS

SELECT SUBSTRING(COMPLETION,1,3) AS MONTH, COUNT(COMPLETION) AS NO_OF_COMPLETED_STUDIES
FROM  (SELECT COMPLETION, STATUS
        FROM CLINICAL_TRIAL 
        WHERE STATUS = 'Completed' AND SUBSTRING(COMPLETION,5,8) == ${hiveconf:YEAR})
GROUP BY MONTH  
ORDER BY CASE MONTH WHEN 'Jan' THEN 1
                    WHEN 'Feb' THEN 2
                    WHEN 'Mar' THEN 3
                    WHEN 'Apr' THEN 4
                    WHEN 'May' THEN 5
                    WHEN 'Jun' THEN 6
                    WHEN 'Jul' THEN 7
                    WHEN 'Aug' THEN 8
                    WHEN 'Sep' THEN 9
                    WHEN 'Oct' THEN 10
                    WHEN 'Nov' THEN 11
                    WHEN 'Dec' THEN 12
END;
SELECT * FROM COMPLETED_STUDIES_2021

-- COMMAND ----------

SELECT * FROM COMPLETED_STUDIES_2021

-- COMMAND ----------

-- DBTITLE 1,Further Analysis on Question 5
SELECT SPONSOR, COUNT(SPONSOR) AS FREQUENCY
  FROM (SELECT SPONSOR, PARENT_COMPANY
        FROM CLINICAL_TRIAL CT LEFT JOIN PHARMA P
        ON CT.SPONSOR = P.PARENT_COMPANY)
  WHERE PARENT_COMPANY IS NULL AND SPONSOR NOT LIKE '%Pharma%'
  GROUP BY SPONSOR  
ORDER BY FREQUENCY DESC
LIMIT 10;
